version: '3.8'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest-arm64
    environment: 
      - SERVICES=s3,lambda,logs,dynamodb,iam,ssm,sns,apigateway,cloudwatch
      - DOCKER_HOST=unix:///var/run/docker.sock
      - MSSQL_ACCEPT_EULA=Y
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- } # Only necessay if running the pro version
      - LOCALSTACK_HOST=localstack
    ports: 
      - 4566:4566            # LocalStack Gateway
      - 4510-4559:4510-4559  # external services port range
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks: 
      - demo
networks:
  demo:
